MovieShop/MovieShopMVC/Controllers/CastsController.cs
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
    public class CastsController: Controller
    {
        private ICastService _castService;
        public CastsController(ICastService castService)
        {
            _castService = castService;
        }


        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            //cast service with details
            //pass the cast detail data to view

            var castDetails = await _castService.GetCastDetails(id);
            return View(castDetails);
        }
    }
}

MovieShop/MovieShopMVC/Controllers/MoviesController.cs
using ApplicationCore.Contracts.Repositories;
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Services;

namespace MovieShopMVC.Controllers
{
    public class MoviesController: Controller
    {
        private IMovieService _movieService;
        private readonly ICurrentUser _currentUser;
        private readonly IPurchaseRepository _purchaseRepository;


        public MoviesController(IMovieService movieService, ICurrentUser currentUser, IPurchaseRepository purchaseRepository)
        {
            _movieService = movieService;
            _currentUser = currentUser;
            _purchaseRepository = purchaseRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Details(int Id)
        {
            if (_currentUser.isAuthenticated)
            {
                var userId = _currentUser.UserId;
                bool ispurchased = await _purchaseRepository.IsMoviePurchased(Id, userId);

                if (ispurchased)
                {
                    ViewBag.MoviePurchased = true;
                } 
            }
            else
            {
                ViewBag.MoviePurchased = false;
            };

            //Movie service with details
            //pass the movie detail data to view
            var movieDetails = await _movieService.GetMovieDetails(Id);
            return View(movieDetails);
        }

        [HttpGet]
        public async Task<IActionResult> Genres(int id, int pageSize = 30, int pageNumber = 1)
        {
            var pagedMovies = await _movieService.GetMoviesByGenrePagination(id, pageSize, pageNumber);
            return View("PagedMovies",pagedMovies);
        }

    }
}

MovieShop/MovieShopMVC/Controllers/UserController.cs
using ApplicationCore.Contracts.Services;
using ApplicationCore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Services;
using System.Security.Claims;

namespace MovieShopMVC.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly ICurrentUser _currentUser;
        private readonly IUserService _userService;
        private readonly IMovieService _movieService;


        public UserController(ICurrentUser currentUser, IUserService userService, IMovieService movieService = null)
        {
            _currentUser = currentUser;
            _userService = userService;
            _movieService = movieService;
        }

        [HttpGet]
        public async Task<IActionResult> Purchases()
        {

            var userId = _currentUser.UserId;
            var purchaseDetails = await _userService.GetAllPurchasesForUser(userId);
            return View(purchaseDetails);
        }

        [HttpGet]
        public async Task<IActionResult> Favorites()
        {
            var userId = _currentUser.UserId;
            var favoriteList = await _userService.GetAllFavoritesForUser(userId);
            return View(favoriteList);
        }

        [HttpGet]
        public async Task<IActionResult> Reviews()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> BuyMovie(int movieId)
        {
            var userId = _currentUser.UserId;
            var movieprice = await _movieService.GetMoviePrice(movieId);
            var purchaseModel = new PurchaseRequestModel
            {
                MovieID = movieId,
                UserId = userId,
                PurchaseNumber = Guid.NewGuid(),
                PurchasedDate = DateTime.Now,
                Price = movieprice
            };
            var purchase = await _userService.PurchaseMovie(purchaseModel, userId);
            return RedirectToAction("Purchases");
        }



        [HttpGet]
        public async Task<IActionResult> FavoriteMovies()
        {
            return View();
        }   

}
}

MovieShop/MovieShopMVC/Views/Movies/Details.cshtml
@model ApplicationCore.Models.MovieDetailsModel

<div class="row mt-2">
    <!-- Poster -->
    <div class="col-4">
        <img src="@Model.PosterUrl" alt="@Model.Title" style="width:90%">
    </div>

    <!-- Title, Tagline, Information -->

     <div class="col-md-5">
        <h3>@Model.Title</h3>
        <p>@Model.Tagline</p>

        @foreach(var genre in @Model.Genres)
        {
            <span class="badge bg-secondary">@genre.Name</span>
        }

        <p><button class="btn btn-primary btn-block">Favorite</button></p>
        @Model.Overview
    </div>

    <div class="col-3">
    <!-- buttons -->

        <div class="span2">

            <!--Review-->
            <p><button class="btn btn-primary btn-block">Review</button></p>
            <!--Buy-->

            @if (@ViewBag.MoviePurchsed == true)
            {
                <button class="btn btn-primary btn-block">Watch Movie</button>
            }else{

            <!-- Button trigger modal -->

            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#buyModal">
              BUY @Model.Price
            </button>

            <form asp-controller="User" asp-action="BuyMovie" method ="post">

            <!-- Modal -->
            <div class="modal fade" id="buyModal" tabindex="-1" role="dialog" aria-labelledby="buymodallabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Purchase Movie: @Model.Title</h5>
                    <input type ="hidden" value = @Model.Id name="MovieId"></input>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    Movie Price is @Model.Price .Purchase?
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

                    <!--Purchase button-->
                    <input type="submit" value = "Purchase Movie" class="btn btn-primary"></input>

                  </div>
                </div>
              </div>
            </div>
            </form>

            }




        </div>
    </div>
</div>

<div class ="row mt-5">
    <!-- Movie Facts -->

    <div class="col-4">
        <h5> MOVIE FACTS</h5>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
              Release Date: 
              <span class="badge bg-secondary">@Model.ReleaseDate</span>
          </li>

          <li class="list-group-item">
              RunTime:
              <span class="badge bg-secondary">@Model.RunTime</span>
          </li>

          <li class="list-group-item">
              Box Office:
              <span class="badge bg-secondary">$@Model.Revenue</span>
          </li>

          <li class="list-group-item">
              Budget:
              <span class="badge bg-secondary">$@Model.Budget</span>
          </li>

        </ul>
    <!-- Trailers -->
        <h5>TRAILERS</h5>
        @foreach( var trailer in @Model.Trailers)
        {
            <p><a href="@trailer.TrailerUrl">@trailer.Name</a></p>

        }

        

    </div>
    <!-- Cast -->

    <div class="col-7 offset-md-1">
        <h5> CAST</h5>
        <ul class="list-group list-group-flush">

        @foreach (var cast in @Model.Casts)
            {
                <li class="list-group-item">
                    <div class = "row">
                       <div class = "col-1">
                           
                           <a asp-action="Details" asp-controller="Casts" asp-route-id="@cast.Id">
                           <img src="@cast.ProfilePath" alt="@cast.Name" class="rounded-circle" style="width:70%">
                           </a>

                       </div>
                       <div class = "col-4">
                           @cast.Name
                       </div>
                       <div class = "col-5">
                           @cast.Character
                       </div>
                    </div>
                </li>
            }
        </ul>


         
        
    </div>



</div>

MovieShop/MovieShopMVC/Views/Movies/PagedMovies.cshtml
@model ApplicationCore.Models.PagedResultSet<ApplicationCore.Models.MovieCardModel>

<div class="rounded">
    <div class="container-fluid bg-light">
        <div class="row">
            @foreach (var movie in Model?.Data)
            {
                <div class="col-6 col-lg-3 col-sm-4 col-xl-2">
                    @*<partial name="MovieCard" model="movie"/>*@
                    @await Html.PartialAsync("_MovieCard", movie)
                </div>
            }

        </div>
    </div>
</div>


<nav aria-label="Page navigation example">
    <ul class="pagination">

        @for (var i = 1; i <= Model.TotalPages; i++)
        {
            
            <li class="page-item">
                <a class="page-link" asp-route-pageNumber = "@i" asp-action="Genres" >
                    @i
                </a>
            </li>



        }


    </ul>


</nav>